[package]
name = "frei0r-sys"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://gitlab.com/kwokkinming/frei0r-rs"
description = "Sys crate for frei0r-rs"

[build-dependencies]
bindgen = "0.69.4"
