[package]
name = "frei0r-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://gitlab.com/kwokkinming/frei0r-rs"

[[example]]
name = "shift"
crate-type = ["cdylib"]

[dependencies]
frei0r-macros = { version = "0.1.0", path = "../frei0r-macros" }
frei0r-sys = { version = "0.1.0", path = "../frei0r-sys" }
