[package]
name = "frei0r-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
frei0r-macros = { version = "0.1.0", path = "../frei0r-macros" }
frei0r-sys = { version = "0.1.0", path = "../frei0r-sys" }
