[package]
name = "frei0r-macros"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://gitlab.com/kwokkinming/frei0r-rs"
description = "Macros crate for frei0r-rs"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.84"
quote = "1.0.36"
syn = "2.0.66"
